
post http://localhost:4444/exercises
Content-Type: application/json

{
  "number": "2.14",
  "instruction": "Перекладіть наступні питання на німецьку мову:",
  "tasks": [
    {
      "content": "Ти дизайнер?",
      "solution": ["Bist du Designer?"]
    },
    {
      "content": "Ти програміст?",
      "solution": ["Bist du Programmierer?"]
    },
    {
      "content": "Ти менеджер?",
      "solution": ["Bist du Manager?"]
    },
    {
      "content": "Ти робітник?",
      "solution": ["Bist du Arbeiter?"]
    },
    {
      "content": "Він спортсмен?",
      "solution": ["Ist er Sportler?"]
    },
    {
      "content": "Він вчитель?",
      "solution": ["Ist er Lehrer?"]
    },
    {
      "content": "Він великий?",
      "solution": ["Ist er groß?"]
    },
    {
      "content": "Він новий?",
      "solution": ["Ist er neu?"]
    },
    {
      "content": "Ви дизайнери?",
      "solution": ["Seid ihr Designer?"]
    },
    {
      "content": "Ви робітники?",
      "solution": ["Seid ihr Arbeiter?"]
    },
    {
      "content": "Ви спортсмени?",
      "solution": ["Seid ihr Sportler?"]
    },
    {
      "content": "Ви вчителі?",
      "solution": ["Seid ihr Lehrer?"]
    },
    {
      "content": "Ви програмісти?",
      "solution": ["Seid ihr Programmierer?"]
    },
    {
      "content": "Ви дизайнери?",
      "solution": ["Seid ihr Designer?"]
    },
    {
      "content": "Вони менеджери?",
      "solution": ["Sind sie Manager?"]
    },
    {
      "content": "Вони спортсмени?",
      "solution": ["Sind sie Sportler?"]
    },
    {
      "content": "Вони робітники?",
      "solution": ["Sind sie Arbeiter?"]
    },
    {
      "content": "Вони старі?",
      "solution": ["Sind sie alt?"]
    },
    {
      "content": "Цей поїзд новий?",
      "solution": ["Ist dieser Zug neu?"]
    },
    {
      "content": "Ця газета цікава?",
      "solution": ["Ist diese Zeitung interessant?"]
    }
  ]
}

###
get http://localhost:4444/modules

###
get http://localhost:4444/modules/656c33a76703257fb1ee14dd

###
get http://localhost:4444/modules/656c33a76703257fb1ee14dd/exercises

###
get http://localhost:4444/exercises

###

put http://localhost:4444/exercises/6574a1258a71715508c69d2d/6574a1258a71715508c69d3d/update-field
Content-Type: application/json

# {
#   "fieldToUpdate": "content",
#   "updatedValue": "Das {{input}} ist schlecht."
# }


###
get http://localhost:4444/exercises/6574c2608ad53e5b6ac6786b

###
get http://localhost:4444/exercises/6574da685b14c03f7112154f

###
post http://localhost:4444/auth/register
Content-Type: application/json

{
  "email": "andygrigs88@gmail.com",
  "password": "123123",
  "fullName": "Andy Grigs"
}


###
post http://localhost:4444/auth/login
Content-Type: application/json

{
  "email": "andygrigs88@gmail.com",
  "password": "123123"
}
###
post http://localhost:4444/progress/update/65c67d4265b19d7d5ff7c4d2
Content-Type: application/json

{
  "moduleId": "656c33a76703257fb1ee14dd",
  "exerciseId": "6574a1258a71715508c69d2d",
  "exerciseProgress":  75,
  "exerciseCompleted": true
}

###
post http://localhost:4444/update/exercise/65c67d4265b19d7d5ff7c4d2
Content-Type: application/json

{
  "userId": "60d5ecb8b392d73f8c123abc",
  "exercise": {
    "exerciseId": "1111111111111111123",
    "progress":  75,
    "completed": false
  }
}


###

post http://localhost:4444/progress/module/create/65ca3c59224df645ddd39a2b
Content-Type: application/json


  {
    "moduleId": "120938120",
    "moduleNumber": 1,
    "progress": 17,
    "completed": "true"
  }
 

 

###

put http://localhost:4444/progress/module/update/65ca3c59224df645ddd39a2b
Content-Type: application/json

  {
    "moduleId": "120938120123",
    "progress": 99,
    "completed":"true"
  }
 
### 

get http://localhost:4444/progress/exercise/65ca3c59224df645ddd39a2b/9345102394820


###

put http://localhost:4444/progress/exercise/update/65ca3c59224df645ddd39a2b
Content-Type: application/json

 {
  "exerciseId": "2",
  "progress":  13,
  "completed": false
}
  


###
post http://localhost:4444/progress/exercise/create/65ca3c59224df645ddd39a2b
Content-Type: application/application/json

{
  "exerciseId": "1",
  "exerciseNumber": 1 ,
  "exerciseAnswers": {
  },
  "progress":  1,
  "completed": false
}
